# This is a basic workflow to help you get started with Actions

name: build-wwiser

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - master
    - test_actions
    paths: # Only run on code change
    - "wwiser/**/*.py"
    - "wwiser.py"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "dist"
  release-new-version:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Get Release Version
        id: release_version
        run: echo "::set-output name=wwiser_version::$(Get-Date -Format 'yyyyMMdd')"
            
      - name: Build WWiser
        env:
          wwiser_version: ${{ steps.release_version.outputs.wwiser_version }}
        run: python build.py ${{ env.wwiser_version }}
        
      - name: Create Release
        id: make_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          wwiser_version: v${{ steps.release_version.outputs.wwiser_version }}
        with:
          tag_name: ${{ env.wwiser_version }}
          release_name: ${{ env.wwiser_version }}
          draft: false
          prerelease: false
          
      - name: Upload Binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.make_release.outputs.upload_url }}
          asset_path: ./bin/wwiser.pyz
          asset_name: wwiser.pyz
          asset_content_type: application/octet-stream
